Repository UCSD/campus-mobile, pull requests merged in 2024-10, with the labels that each got.

#2032 Card reordering enhancement 1996
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/providers/cards.dart
  lib/ui/profile/cards.dart
  lib/ui/profile/profile.dart
  lib/ui/student_id/student_id_card.dart
Labels: Needs Tester

#2078 Implemented the finally block on applicable try/catch statements.
  lib/app_constants.dart
  lib/app_networking.dart
  lib/core/providers/cards.dart
  lib/core/providers/events.dart
  lib/core/providers/map.dart
  lib/core/providers/messages.dart
  lib/core/providers/news.dart
  lib/core/providers/notices.dart
  lib/core/providers/notifications.dart
  lib/core/providers/notifications_freefood.dart
  lib/core/providers/scanner.dart
  lib/core/providers/scanner_message.dart
  lib/core/providers/speed_test.dart
  lib/core/providers/user.dart
  lib/core/services/availability.dart
  lib/core/services/barcode.dart
  lib/core/services/cards.dart
  lib/core/services/classes.dart
  lib/core/services/dining.dart
  lib/core/services/employee_id.dart
  lib/core/services/events.dart
  lib/core/services/map.dart
  lib/core/services/messages.dart
  lib/core/services/news.dart
  lib/core/services/notices.dart
  lib/core/services/notifications.dart
  lib/core/services/notifications_freefood.dart
  lib/core/services/parking.dart
  lib/core/services/scanner_message.dart
  lib/core/services/shuttle.dart
  lib/core/services/speed_test.dart
  lib/core/services/spot_types.dart
  lib/core/services/student_id.dart
  lib/core/services/triton_media.dart
  lib/core/services/user.dart
  lib/core/services/weather.dart
  lib/ui/mystudentchart/mystudentchart_card.dart
  lib/ui/myucsdchart/myucsdchart_card.dart
  lib/ui/notices/notices_card.dart
  lib/ui/profile/profile.dart
  lib/ui/wifi/wifi_card.dart
Labels: In Testing

#2090 Revert "Merge pull request #1932 from mliu6723/podcast_feature"
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/edu/ucsd/MainActivity.kt
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  lib/app_constants.dart
  lib/app_provider.dart
  lib/app_router.dart
  lib/core/models/triton_media.dart
  lib/core/providers/triton_media.dart
  lib/core/services/triton_media.dart
  lib/main.dart
  lib/ui/home/home.dart
  lib/ui/onboarding/onboarding_initial_screen.dart
  lib/ui/triton_media/triton_media_card.dart
  lib/ui/triton_media/triton_media_detail_view.dart
  lib/ui/triton_media/triton_media_list.dart
  lib/ui/triton_media/triton_media_tile.dart
  lib/ui/triton_media/triton_media_view_all.dart
  pubspec.lock
  pubspec.yaml
Labels: 7.28
