Repository UCSD/campus-mobile, pull requests merged in 2025-08, with the labels that each got.

#2220 (CAAPP-416) What's Around Me [With Points of Interest]
  lib/app_constants.dart
  lib/core/models/wam.dart
  lib/core/services/wam.dart
  lib/ui/map/map.dart
  lib/ui/map/more_results_list.dart
  lib/ui/map/wam.dart
Labels: Feature, Testing Pass

#2231 [CAAP-453] iOS Black Space Under Navbar Fix
  lib/main.dart
Labels: In Testing

#2223 [CAAPP-432] Upgrade "Dio" Dependency Package
  lib/app_networking.dart
  pubspec.lock
  pubspec.yaml
Labels: In Testing, dependencies

#2233 (CAAPP-450) Standardize public data networking
  lib/core/services/availability.dart
  lib/core/services/shuttle.dart
Labels: Needs Tester

#2236 [CAAP-418] - Add Parking Spots (EV, PV, 2 Person Carpool)
  lib/app_constants.dart
  lib/core/models/spot_types.dart
  lib/core/providers/parking.dart
  lib/ui/parking/circular_parking_indicator.dart
  lib/ui/parking/spot_types_view.dart
Labels: Needs Tester

#2215 [CAAP-424] Fix manage spots bug
  lib/ui/parking/parking_card.dart
Labels: Testing Pass
